import { CompetitiveService } from './competitive.js';
import { WebProfileService } from './web-profile.js';

export class MonitorService {
 constructor({db=null,fetchFn=globalThis.fetch,now=()=>new Date()}={}){this.db=db;this.fetchFn=fetchFn;this.now=now;}
 configured(){return Boolean(this.db?.prepare)}
 async create({name,type,target,intervalMinutes=1440}){if(!this.configured())return noDb();const id=crypto.randomUUID();const now=this.now().toISOString();const next=new Date(this.now().getTime()+intervalMinutes*60000).toISOString();await this.db.prepare(`INSERT INTO monitors(id,name,type,target,interval_minutes,enabled,next_run_at,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?,?)`).bind(id,name,type,target,intervalMinutes,next,now,now).run();return{ok:true,id,name,type,target,intervalMinutes,nextRunAt:next};}
 async list(){if(!this.configured())return noDb();const r=await this.db.prepare(`SELECT id,name,type,target,interval_minutes,enabled,last_run_at,next_run_at,created_at,updated_at FROM monitors ORDER BY created_at DESC`).all();return{ok:true,monitors:r?.results??[]};}
 async run(id){if(!this.configured())return noDb();const row=await this.db.prepare(`SELECT * FROM monitors WHERE id=?`).bind(id).first();if(!row)return{ok:false,reason:'not_found'};const payload=await this.#collect(row.type,row.target);const json=JSON.stringify(payload);const hash=await sha256(json);const prev=await this.db.prepare(`SELECT id,content_hash,payload_json,observed_at FROM snapshots WHERE monitor_id=? ORDER BY observed_at DESC LIMIT 1`).bind(id).first();const changed=!prev||prev.content_hash!==hash;const observed=this.now().toISOString();await this.db.prepare(`INSERT INTO snapshots(id,monitor_id,content_hash,payload_json,observed_at) VALUES(?,?,?,?,?)`).bind(crypto.randomUUID(),id,hash,json,observed).run();if(changed&&prev){await this.db.prepare(`INSERT INTO intelligence_events(id,monitor_id,event_type,summary,previous_hash,current_hash,created_at) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),id,'change_detected',`Change detected for ${row.target}`,prev.content_hash,hash,observed).run();}const next=new Date(this.now().getTime()+Number(row.interval_minutes)*60000).toISOString();await this.db.prepare(`UPDATE monitors SET last_run_at=?,next_run_at=?,updated_at=? WHERE id=?`).bind(observed,next,observed,id).run();return{ok:true,id,changed,previousHash:prev?.content_hash??null,currentHash:hash,observedAt:observed,nextRunAt:next,payload};}
 async runDue({limit=5}={}){if(!this.configured())return noDb();const now=this.now().toISOString();const r=await this.db.prepare(`SELECT id FROM monitors WHERE enabled=1 AND next_run_at<=? ORDER BY next_run_at ASC LIMIT ?`).bind(now,limit).all();const results=[];for(const row of r?.results??[])results.push(await this.run(row.id));return{ok:true,ran:results.length,results};}
 async events({monitorId=null,limit=50}={}){if(!this.configured())return noDb();const sql=monitorId?`SELECT * FROM intelligence_events WHERE monitor_id=? ORDER BY created_at DESC LIMIT ?`:`SELECT * FROM intelligence_events ORDER BY created_at DESC LIMIT ?`;const stmt=this.db.prepare(sql);const r=monitorId?await stmt.bind(monitorId,limit).all():await stmt.bind(limit).all();return{ok:true,events:r?.results??[]};}
 async #collect(type,target){if(type==='web_profile')return new WebProfileService({fetchFn:this.fetchFn}).inspect(target);if(type==='competitive_snapshot')return new CompetitiveService({fetchFn:this.fetchFn}).snapshot(target);throw new Error(`Unsupported monitor type: ${type}`)}
}
function noDb(){return{ok:false,reason:'dataset_not_configured',detail:'Bind D1 as DB and apply migrations.'}}
async function sha256(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
